def parse(input, io)
  comment_token = "//"
  private_token = "===BEGIN PRIVATE DOMAINS==="
  section = nil # 1 == ICANN, 2 == PRIVATE

  io.puts "  l = PublicSuffix::List.new"
  c = 0

  input.each_line do |line|
    line = line.strip

    case
    when line.empty?
      # skip
    when line.includes?(private_token)
      section = 2
    when line.starts_with?(comment_token)
      # skip
    else
      if section == 2
        io.puts("  l.add(\"#{line}\", true)")
      else
        io.puts("  l.add(\"#{line}\")")
      end
      c += 1
    end
  end

  io.puts("  l")
  c
end

filename = (ARGV[0]? || "").to_s
f = File.read(filename)

io = STDOUT

io.puts "# this list autogenerated, not edit it, generated at #{Time.now}"
io.puts("def PublicSuffix.generated_list")
c = parse(f, io)
io.puts("end")
STDERR.puts("Generated for #{c} lines")
